services:
  ws-server:
    build:
      context: ./turborepo
      dockerfile: Dockerfile
    env_file:
      - ./turborepo/apps/ws-server/.env
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - python-image-service

  python-image-service:
    build: 
      context: ./python
      dockerfile: Dockerfile
    env_file:
      - ./python/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 2s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
