services:
  ws-server:
    build:
      context: ./turborepo
      dockerfile: Dockerfile
    env_file:
      - ./turborepo/apps/ws-server/.env
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - python-image-service
      - postgres
    environment:
      # Make sure your ws-server env points to the local Postgres
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/t3chatdb

  python-image-service:
    build:
      context: ./python
      dockerfile: Dockerfile
    env_file:
      - ./python/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      # Example for FastAPI if it connects to Postgres too
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/t3chatdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 2s
      retries: 5

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 2s
      retries: 5

  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: t3chatdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
