services:
  ws-server:
    build: ./turborepo/apps/ws-server
    env_file:
      - ./turborepo/apps/ws-server/.env
    ports:
      - "4000:4000"
    depends_on:
      - python-image-service
      - redis

  python-image-service:
    build: ./python
    env_file:
      - ./python/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
