/**
 * api-handling types for codegen
 */
export type {
  AnthropicError,
  AnthropicModel,
  AnthropicResponse,
  AnthropicSuccess,
  GeminiError,
  GeminiModel,
  GeminiResponse,
  GeminiSuccess,
  GrokModelsResponse,
  ListModelsSingleton,
  MultimodalRT,
  OpenAiError,
  OpenAiResponse,
  SuccessResponse
} from "@/codegen-types.ts";

export type {
  AIChatRequestImgGenFields,
  AIChatResponseImgGenFields,
  AIChatResponseImgGenFieldsFinal,
  AIChatResponseImgGenSubFields,
  Dalle2ImgGenWorkupRT,
  Dalle2Opts,
  Dalle2OutputSize,
  Dalle3ImgGenWorkupRT,
  Dalle3Opts,
  Dalle3OutputSize,
  GeminiImageQuality,
  GeminiImageSize,
  GeminiModelAspectRatio,
  GeminiModelAspectRatioWorkup,
  GoogleGenAIImageGenOpts,
  GoogleHarmCategory,
  GoogleImagePromptLanguage,
  GoogleImagenGenerateImagesConfig,
  GoogleImgOutputFormat,
  GoogleImgSizeQualityOpts,
  GooglePersonGeneration,
  GoogleSafetyFilterLevel,
  GptImageAndFacilitatorsImgGenWorkupRT,
  GptImage1Opts,
  GptImageOutputSize,
  GrokImageGenOpts,
  ImageGenOptsByProvider,
  ImageGenPartialArr,
  ImagenOptions,
  ImagenOutputSize,
  ImgGenStage,
  ImgGenWorkupRT,
  ImgGenWorkupRTObj,
  ImgGenWorkupResRT,
  ImgMetadataEntity,
  NanoBananaImageGenOpts,
  NanoBananaOutputSize,
  OpenAIImageGenOpts,
  OpenAIImgCapableModels,
  OpenAIImgNativeGPTImgAR,
  OpenAIModelAspectRatio,
  OpenAIModelAspectRatioWorkup,
  OpenAINativeImgModelAspectRatioWorkup,
  OpenAINativeImgModelQualityWorkup,
  OpenAISizeQualityOpts,
  OutputSizeProps,
  S3Checksum,
  S3StorageClass,
  SharedOpenAIImageOpts
} from "@/events-images.ts";

export type {
  AIChatEventTypeUnion,
  AssetDraftId,
  AssetOrigin,
  AssetStatus,
  AssetUploadAbortReason,
  AssetUploadInstructionsMethod,
  AttachmentMetadata,
  ClientContextWorkupProps,
  DocExtensions,
  EbookExtensions,
  DocSpecs,
  ImageSpecs,
  ImgColorModel,
  ImgColorSpace,
  ImgFormat,
  MetadataMap,
  MetadataTypeMap,
  MetadataTypeUnion,
  MetadataUnion,
  PdfDocSpecs,
  PresentationDocSpecs,
  PresentationExtensions,
  RecordCountsProps,
  S3ObjectId,
  SpreadSheetDocSpecs,
  SpreadSheetExtensions,
  TextExtensions,
  UnknownSpecs,
  UploadMethod,
  UserMetadata,
  WithExpiry
} from "@/events-workup.ts";

/**
 * shared websocket (client-server) events
 */
export type {
  AIChatChunk,
  AIChatError,
  AIChatInlineData,
  AIChatRequest,
  AIChatResEntity,
  AIChatResponse,
  AIChatResponseDb,
  AIChatResRT,
  AnyEvent,
  AnyEventTypeUnion,
  AssetAttachedToMessage,
  AssetBatchUpload,
  AssetDeleted,
  AssetFetchError,
  AssetFetchRequest,
  AssetFetchResponse,
  AssetPasteEvent,
  AssetReady,
  AssetUploadAbort,
  AssetUploadAborted,
  AssetUploadComplete,
  AssetUploadCompleteError,
  AssetUploadError,
  AssetUploadInstructions,
  AssetUploadPrepare,
  AssetUploadProgress,
  AssetUploadedNotification,
  AssetUploadRequest,
  AssetUploadResponse,
  ChatWsEvent,
  ChatWsEventTypeUnion,
  ConnectionEstablished,
  EventMap,
  EventTypeMap,
  ImageGenError,
  ImageGenProgress,
  ImageGenRequest,
  ImageGenResponse,
  PingMessage,
  ProviderContextPing,
  ProviderContextPong,
  ProviderContextUpdate,
  ProviderContextUpdateAck,
  TypingIndicator
} from "@/events.ts";

/**
 * model/provider types
 */
export type {
  AllDisplayNamesUnion,
  AllImgGenFacilitatingModelsUnion,
  AllImgGenModelsUnion,
  AllImgGenProviderModelMap,
  AllImgGenProviderModels,
  AllModelsUnion,
  AllVideoGenModels,
  AnthropicChatModels,
  AnthropicDisplayNameUnion,
  AnthropicModelIdUnion,
  DisplayNameModelMap,
  GeminiChatModels,
  GeminiDisplayNameUnion,
  GeminiDisplayNameUnionImgGen,
  GeminiDisplayNameUnionVideoGen,
  GeminiImgGenFacilitatingModels,
  GetImgGenFacilitatingModelUtilRT,
  GeminiImgGenModels,
  GeminiModelIdUnion,
  GeminiModelIdUnionImgGen,
  GeminiModelIdUnionVideoGen,
  GeminiVideoGenModels,
  GetDisplayNamesForProviderRT,
  GetDisplayNamesForProviderRTImgGen,
  GetDisplayNamesForProviderRTVideoGen,
  GetImgModelUtilRT,
  GetAllImgGenModelUtilRt,
  GetModelsForProviderRT,
  GetModelsForProviderRTImgGen,
  GetModelsForProviderRTVideoGen,
  GetModelUtilRT,
  GetVideoModelUtilRT,
  GrokChatModels,
  GrokDisplayNameUnion,
  GrokDisplayNameUnionImgGen,
  GrokImgGenModels,
  GrokModelIdUnion,
  GrokModelIdUnionImgGen,
  ImageGenFacilitatingModelsByProvider,
  ImageGenFacilitatingProviders,
  ImgGenFacilitatingModelMap,
  ImageGenModels,
  ImageGenModelsByProvider,
  ImageGenProviders,
  ImgGenModelMap,
  MetaChatModels,
  MetaDisplayNameUnion,
  MetaModelIdUnion,
  ModelDisplayNameToModelId,
  ModelDisplayNameToModelIdImgGen,
  ModelIdToModelDisplayName,
  ModelIdToModelDisplayNameImgGen,
  ModelDisplayNameToModelIdVideoGen,
  ModelIdToModelDisplayNameVideoGen,
  ModelMap,
  Models,
  OpenAIChatModels,
  OpenAiDisplayNameUnion,
  OpenAiDisplayNameUnionImgGen,
  OpenAIImgGenFacilitatingModels,
  OpenAIImgGenModels,
  OpenAiModelIdUnionImgGen,
  OpenAiModelIdUnion,
  OpenAIVideoGenModels,
  OpenAiDisplayNameUnionVideoGen,
  OpenAiModelIdUnionVideoGen,
  Provider,
  Providers,
  VercelChatModels,
  VercelDisplayNameUnion,
  VercelModelIdUnion,
  VideoGenModelMap,
  VideoGenProviders
} from "@/models.ts";

export {
  allProviders,
  allImgGenProviders,
  allImgSupportingProviderModels,
  allVideoGenProviders,
  audioMimeSupportByProvider,
  defaultModelDisplayNameByProvider,
  defaultModelIdByProvider,
  displayNameModelsByProvider,
  displayNameToModelId,
  displayNameModelsByProviderImgGen,
  displayNameModelsByProviderVideoGen,
  displayNameToModelIdImgGen,
  displayNameToModelIdVideoGen,
  docMimeSupportByProvider,
  getAllProviders,
  getAllImgGenProviders,
  getAllVideoGenProviders,
  getDisplayNameByModelId,
  getDisplayNamesForProvider,
  getDisplayNamesForProviderImgGen,
  getDisplayNamesForProviderVideoGen,
  getModelIdByDisplayName,
  getModelsForProvider,
  getModelsForProviderImgGen,
  getModelsForProviderVideoGen,
  imageGenFacilitatingProviders,
  imageGenProviders,
  imgMimeSupportByProvider,
  imageModelFacilitatorSets,
  imageModelSets,
  modelIdsByProvider,
  modelIdToDisplayName,
  modelIdToDisplayNameImgGen,
  modelIdToDisplayNameVideoGen,
  modelIdsByProviderImgGen,
  modelIdsByProviderVideoGen,
  providerModelChatApi,
  providerModelImageGenApi,
  providerModelImageGenFacilitatingApi,
  toPrismaFormat,
  videoMimeSupportByProvider
} from "@/models.ts";

/**
 * convenient utility types
 */
export type {
  ArrFieldReplacer,
  CTR,
  DeepPartial,
  DeepPartialFields,
  DeepReplace,
  DX,
  Equal,
  Expect,
  Extends,
  InferGSPRT,
  InferGSPRTWorkup,
  IsExact,
  IsOptional,
  OnlyOptional,
  OnlyRequired,
  RTC,
  RequireNested,
  Rm,
  TCN,
  Unenumerate,
  Without,
  XOR
} from "@/utils.ts";

export { createDraftId, parseDraftId } from "@/utils.ts";

/**
 * domain level types
 */
export type {
  AccountSingleton,
  AttachmentProviderSingleton,
  AssetReadyPayload,
  AttachmentSingleton,
  BigIntOrNumber,
  ConversationSingleton,
  ConversationSingletonOneOff,
  ConvoSettingsSingleton,
  DocumentSingleton,
  FlexiProvider,
  ImageGenJobSingleton,
  ImageGenOutputSingleton,
  ImageSingleton,
  MessageSingleton,
  ProfileSingleton,
  ProviderStoreDocumentSingleton,
  ProviderStoreSingleton,
  SessionSingleton,
  SettingsSingleton,
  Signals,
  UserKeySingleton,
  UserSingleton
} from "@/types.ts";

declare global {
  interface JSON {
    parse<T = unknown>(
      text: string,
      reviver?: (this: any, key: string, value: any) => any
    ): T;
  }
  interface Body {
    json<T = unknown>(): Promise<T>;
  }
}
