export type {
  AIChatEventTypeUnion,
  AssetDraftId,
  AssetOrigin,
  AssetStatus,
  AssetUploadAbortReason,
  AssetUploadInstructionsMethod,
  AttachmentMetadata,
  ClientContextWorkupProps,
  Dalle2Opts,
  Dalle3Opts,
  DocExtensions,
  EbookExtensions,
  DocSpecs,
  GoogleGenAIImageGenOpts,
  GptImage1Opts,
  GrokImageGenOpts,
  ImageGenOptsByProvider,
  ImagenOptions,
  ImageSpecs,
  ImgColorModel,
  ImgColorSpace,
  ImgFormat,
  ImgGenStage,
  MetadataMap,
  MetadataTypeMap,
  MetadataTypeUnion,
  MetadataUnion,
  NanoBananaImageGenOpts,
  OpenAIImageGenOpts,
  OpenAISizeQualityOpts,
  PdfDocSpecs,
  PresentationDocSpecs,
  PresentationExtensions,
  RecordCountsProps,
  S3ObjectId,
  SharedOpenAIImageOpts,
  SpreadSheetDocSpecs,
  SpreadSheetExtensions,
  TextExtensions,
  UnknownSpecs,
  UploadMethod,
  UserMetadata,
  WithExpiry
} from "@/events-workup.ts";

/**
 * shared websocket (client-server) events
 */
export type {
  AIChatChunk,
  AIChatError,
  AIChatInlineData,
  AIChatRequest,
  AIChatRequestImgGenFields,
  AIChatResEntity,
  AIChatResponse,
  AIChatResponseImgGenFields,
  AnyEvent,
  AnyEventTypeUnion,
  AssetAttachedToMessage,
  AssetBatchUpload,
  AssetDeleted,
  AssetFetchError,
  AssetFetchRequest,
  AssetFetchResponse,
  AssetPasteEvent,
  AssetReady,
  AssetUploadAbort,
  AssetUploadAborted,
  AssetUploadComplete,
  AssetUploadCompleteError,
  AssetUploadError,
  AssetUploadInstructions,
  AssetUploadPrepare,
  AssetUploadProgress,
  AssetUploadedNotification,
  AssetUploadRequest,
  AssetUploadResponse,
  ChatWsEvent,
  ChatWsEventTypeUnion,
  EventMap,
  EventTypeMap,
  ImageGenError,
  ImageGenProgress,
  ImageGenRequest,
  ImageGenResponse,
  PingMessage,
  TypingIndicator
} from "@/events.ts";

/**
 * model/provider types
 */
export type {
  AllDisplayNamesUnion,
  AllImgGenFacilitatingModelsUnion,
  AllImgGenModelsUnion,
  AllModelsUnion,
  AnthropicChatModels,
  AnthropicDisplayNameUnion,
  AnthropicModelIdUnion,
  DisplayNameModelMap,
  GeminiChatModels,
  GeminiDisplayNameUnion,
  GeminiImgGenFacilitatingModels,
  GetImgGenFacilitatingModelUtilRT,
  GeminiImgGenModels,
  GeminiModelIdUnion,
  GetDisplayNamesForProviderRT,
  GetImgModelUtilRT,
  GetModelsForProviderRT,
  GetModelUtilRT,
  GrokChatModels,
  GrokDisplayNameUnion,
  GrokImgGenModels,
  GrokModelIdUnion,
  ImageGenFacilitatingModelsByProvider,
  ImageGenFacilitatingProviders,
  ImgGenFacilitatingModelMap,
  ImageGenModels,
  ImageGenModelsByProvider,
  ImageGenProviders,
  ImgGenModelMap,
  MetaChatModels,
  MetaDisplayNameUnion,
  MetaModelIdUnion,
  ModelDisplayNameToModelId,
  ModelIdToModelDisplayName,
  ModelMap,
  Models,
  OpenAIChatModels,
  OpenAiDisplayNameUnion,
  OpenAIImgGenFacilitatingModels,
  OpenAIImgGenModels,
  OpenAiModelIdUnion,
  Provider,
  Providers,
  VercelChatModels,
  VercelDisplayNameUnion,
  VercelModelIdUnion
} from "@/models.ts";

export {
  allProviders,
  audioMimeSupportByProvider,
  defaultModelDisplayNameByProvider,
  defaultModelIdByProvider,
  displayNameModelsByProvider,
  displayNameToModelId,
  docMimeSupportByProvider,
  getAllProviders,
  getDisplayNameByModelId,
  getDisplayNamesForProvider,
  getModelIdByDisplayName,
  getModelsForProvider,
  imageGenProviders,
  imgMimeSupportByProvider,
  imageModelSets,
  modelIdsByProvider,
  modelIdToDisplayName,
  providerModelChatApi,
  providerModelImageGenApi,
  toPrismaFormat,
  videoMimeSupportByProvider
} from "@/models.ts";

/**
 * convenient utility types
 */
export type {
  ArrFieldReplacer,
  CTR,
  DeepPartial,
  DeepPartialFields,
  DeepReplace,
  DX,
  Equal,
  Expect,
  Extends,
  InferGSPRT,
  InferGSPRTWorkup,
  IsExact,
  IsOptional,
  OnlyOptional,
  OnlyRequired,
  RTC,
  RequireNested,
  Rm,
  TCN,
  Unenumerate,
  Without,
  XOR
} from "@/utils.ts";

export { createDraftId, parseDraftId } from "@/utils.ts";

/**
 * api-handling types for codegen
 */

export type {
  AnthropicError,
  AnthropicModel,
  AnthropicResponse,
  AnthropicSuccess,
  AssetReadyPayload,
  AttachmentSingleton,
  BigIntOrNumber,
  ConversationSingleton,
  ConvoSettingsSingleton,
  DocumentSingleton,
  FlexiProvider,
  GeminiError,
  GeminiModel,
  GeminiResponse,
  GeminiSuccess,
  GrokModelsResponse,
  ImageSingleton,
  ListModelsSingleton,
  MessageSingleton,
  OpenAiError,
  OpenAiResponse,
  Signals,
  SuccessResponse
} from "@/types.ts";
