packages:
  - apps/*
  - packages/*
  - tooling/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - cbor-extract
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
