packages:
  - apps/*
  - packages/*
  - tooling/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - cbor-extract
  - esbuild
  - msgpackr-extract
  - oxc-resolver
  - prisma
  - protobufjs
  - puppeteer
  - sharp
  - unrs-resolver

patchedDependencies:
  openai@6.7.0: patches/openai@6.7.0.patch
