export type ImageGenProps = {
  messages: {
    id: string;
    conversationId: string;
    userId: string | null;
    senderType: string;
    provider: string;
    model: string;
    userKeyId: string;
    content: string;
    thinkingText?: string | null;
    thinkingDuration?: string | null;
    isImageGen: boolean;
    messageType: string;
    liked: boolean;
    disliked: boolean;
    tryAgain: boolean;
    createdAt: string;
    updatedAt: string;
    imageGenJob: {
      id: string;
      requestMessageId: string;
      provider: string;
      model: string;
      userId: string;
      userKeyId: string;
      keyFingerprint: string | null;
      prompt: string;
      systemPrompt: string | null;
      temperature: string | null;
      topP: number | null;
      nRequested: number;
      nCompleted: number;
      seed: number | null;
      negativePrompt: string | null;
      outputSize: string;
      outputQuality: string;
      outputFormat: string;
      outputBackground: string;
      outputCompression: string | null;
      partialImagesRequested: number;
      inputFidelity: string;
      personGeneration: string | null;
      moderation: string;
      stage: string;
      progress: number;
      etaSeconds?: number | null;
      durationMs: number;
      usage?: number | null;
      revisedPrompt: string;
      error?: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
    attachments?: {
      id: string;
      conversationId: string | null;
      draftId: string | null;
      batchId: string | null;
      generationGroupId: string;
      seriesId: string;
      userId: string;
      messageId: string;
      s3ObjectId: string;
      origin: string;
      status: string;
      uploadMethod: string;
      assetType: string;
      uploadDuration: number;
      cdnUrl: string;
      publicUrl: string | null;
      sourceUrl: string | null;
      thumbnailKey: string | null;
      compatMime: string;
      compatExt: string;
      compatVersionId: string;
      compatKey: string;
      compatS3ObjectId: string;
      compatStatus: string;
      compatReadyAt: string;
      compatCdnUrl: string;
      bucket: string;
      key: string;
      versionId: string;
      region: string;
      cacheControl: string | null;
      contentDisposition: string | null;
      contentEncoding: string | null;
      expiresAt: number | null;
      size: number;
      filename: string;
      ext: string;
      mime: string;
      etag: string;
      checksumAlgo: string;
      checksumSha256: string;
      storageClass: string | null;
      sseAlgorithm: string | null;
      sseKmsKeyId: string | null;
      s3LastModified: string;
      deletedAt: string | null;
      createdAt: string;
      updatedAt: string;
      imageGenOutput: {
        id: string;
        jobId: string;
        jobIndex: number;
        kind: string;
        seriesIndex: number;
        seriesId: string;
        isPartial: boolean;
        attachmentId: string;
        width: number;
        height: number;
        mime: string;
        ext: string;
        revisedPrompt: string;
        createdAt: string;
        updatedAt: string;
      };
      image: {
        attachmentId: string;
        format: string;
        width: number;
        height: number;
        aspectRatio: number;
        frames: number;
        hasAlpha: boolean;
        animated: boolean;
        orientation: number | null;
        colorSpace: string;
        exifDateTimeOriginal: string | null;
        cameraMake: string | null;
        cameraModel: string | null;
        lensModel: string | null;
        gpsLat: number | null;
        gpsLon: number | null;
        dominantColorHex: string | null;
        iccProfile: string | null;
        createdAt: string;
        updatedAt: string;
      };
    }[];
  }[];
  id: string;
  userId: string;
  userKeyId: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  branchId: string | null;
  parentId: string | null;
  isShared: boolean;
  shareToken: null | string;
};
