export const displayNameModelsByProvider = {
  openai: [
    "GPT-5.6 Sol",
    "GPT-5.6 Terra",
    "GPT-5.6 Luna",
    "GPT-5.5",
    "GPT-5.4",
    "GPT-5.4 mini",
    "GPT-5.4 nano",
    "GPT-5.2",
    "GPT-5.2 Chat",
    "GPT-5.1",
    "GPT-5",
    "GPT-5 mini",
    "GPT-5 nano",
    "GPT-5.1 Chat",
    "GPT-5.3 codex",
    "GPT-5.2 codex",
    "GPT-5.1-Codex-Max",
    "GPT-5.1 Codex",
    "GPT-5.1 Codex mini",
    "GPT-5-Codex",
    "GPT-5.5 pro",
    "GPT-5.4 pro",
    "GPT-5.2 pro",
    "GPT-5 pro",
    "GPT-5 Chat",
    "GPT-4.1",
    "GPT-4.1 mini",
    "GPT-4.1 nano",
    "GPT-4o",
    "GPT-4o mini",
    "GPT Image 2",
    "GPT Image 1.5",
    "GPT Image 1",
    "GPT Image 1 mini",
    "chatgpt-4o-latest",
    "o4-mini",
    "o4-mini-deep-research",
    "o3-deep-research",
    "o3",
    "o3-pro",
    "o3-mini",
    "o1",
    "o1-pro",
    "GPT-4",
    "GPT-4 turbo",
    "GPT-3.5 turbo",
    "Sora 2",
    "Sora 2 Pro"
  ],
  gemini: [
    "Gemini 3.7 Flash",
    "Gemini 3.6 Flash",
    "Gemini 3.5 Flash Lite",
    "Gemini 3.5 Flash",
    "Gemini 3.1 Pro Preview",
    "Gemini 3.1 Pro Preview Custom Tools",
    "Gemini 3.1 Flash Lite Preview",
    "Gemini 3 Flash Preview",
    "Nano Banana 2",
    "Nano Banana 2 Lite",
    "Nano Banana Pro",
    "Nano Banana",
    "Gemini Omni Flash Preview",
    "Veo 3.1",
    "Veo 3.1 fast",
    "Veo 3.1 lite",
    "Lyria 3 Pro Preview",
    "Lyria 3 Clip Preview",
    "Gemini 2.5 Pro",
    "Gemini 2.5 Flash",
    "Gemini 2.5 Flash-Lite",
    "Deep Research Max Preview (Apr-21-2026)",
    "Deep Research Preview (Apr-21-2026)",
    "gemini-2.0-flash",
    "gemini-2.0-flash-lite"
  ],
  grok: [
    "Grok 4.6",
    "Grok 4.5",
    "Grok 4.3",
    "Grok 4.20 Multi-Agent",
    "Grok 4.20 Reasoning",
    "Grok 4.20 Non-Reasoning",
    "Grok Build 0.1",
    "Grok Imagine Image 2.0",
    "Grok Imagine Image",
    "Grok Imagine Image Quality",
    "Grok Imagine Video",
    "Grok Imagine Video 1.5"
  ],
  anthropic: [
    "Claude Opus 5",
    "Claude Sonnet 5",
    "Claude Fable 5",
    "Claude Opus 4.8",
    "Claude Opus 4.7",
    "Claude Opus 4.6",
    "Claude Sonnet 4.6",
    "Claude Sonnet 4.5",
    "Claude Opus 4.5",
    "Claude Haiku 4.5"
  ],
  meta: ["Muse Spark 1.2", "Muse Spark 1.1"],
  vercel: ["v0 medium", "v0 medium (legacy)"],
  mistral: [
    "Mistral Small 4",
    "Mistral Medium 3",
    "Mistral Medium 3.5",
    "Mistral Large Latest"
  ],
  cohere: ["Command A Plus", "Command A Reasoning", "Command A"],
  moonshotai: [
    "Kimi K3",
    "Kimi K2.7 Code",
    "Kimi K2.6",
    "Kimi K2.5",
    "Kimi K2 Thinking"
  ],
  deepseek: [
    "DeepSeek V4 Pro",
    "DeepSeek V4 Pro Preview",
    "DeepSeek V4 Flash",
    "DeepSeek R1"
  ],
  zai: ["GLM 5.2", "GLM 5.1", "GLM 5", "GLM 4.7", "GLM 4.6", "GLM 4.5"],
  alibaba: [
    "Qwen3.8-Max",
    "Qwen3.7-Max",
    "Qwen3.7-Plus",
    "Qwen3.7-Flash",
    "Qwen3.6-Plus",
    "Qwen3.5-Plus",
    "Qwen3.5-Flash"
  ],
  minimax: ["MiniMax-M3", "MiniMax-M2.7", "MiniMax-M2.5", "MiniMax-M2.1"],
  sakana: ["Fugu Ultra", "Fugu", "Fugu Cyber", "Sakana Namazu"]
} as const;
