export const displayNameModelsByProvider = {
  openai: [
    "GPT-5.5",
    "GPT-5.4",
    "GPT-5.4 mini",
    "GPT-5.4 nano",
    "GPT-5.2",
    "GPT-5.2 Chat",
    "GPT-5.1",
    "GPT-5",
    "GPT-5 mini",
    "GPT-5 nano",
    "GPT-5.1 Chat",
    "GPT-5.3 codex",
    "GPT-5.2 codex",
    "GPT-5.1-Codex-Max",
    "GPT-5.1 Codex",
    "GPT-5.1 Codex mini",
    "GPT-5-Codex",
    "GPT-5.5 pro",
    "GPT-5.4 pro",
    "GPT-5.2 pro",
    "GPT-5 pro",
    "GPT-5 Chat",
    "GPT-4.1",
    "GPT-4.1 mini",
    "GPT-4.1 nano",
    "GPT-4o",
    "GPT-4o mini",
    "GPT Image 2",
    "GPT Image 1.5",
    "GPT Image 1",
    "GPT Image 1 mini",
    "chatgpt-4o-latest",
    "o4-mini",
    "o4-mini-deep-research",
    "o3-deep-research",
    "o3",
    "o3-pro",
    "o3-mini",
    "o1",
    "o1-pro",
    "GPT-4",
    "GPT-4 turbo",
    "GPT-3.5 turbo",
    "Sora 2",
    "Sora 2 Pro"
  ],
  gemini: [
    "Gemini 3.5 Flash",
    "Gemini 3.1 Pro Preview",
    "Gemini 3.1 Pro Preview Custom Tools",
    "Gemini 3.1 Flash Lite Preview",
    "Gemini 3 Flash Preview",
    "Gemini 2.5 Pro",
    "Nano Banana Pro",
    "Nano Banana 2",
    "Nano Banana",
    "Gemini 2.5 Flash",
    "Gemini 2.5 Flash-Lite",
    "Deep Research Pro Preview (Dec-12-2025)",
    "Deep Research Max Preview (Apr-21-2026)",
    "Deep Research Preview (Apr-21-2026)",
    "Gemini 2.0 Flash",
    "Gemini 2.0 Flash-Lite",
    "Imagen 4",
    "Imagen 4 Fast",
    "Imagen 4 Ultra",
    "Veo 3.1",
    "Veo 3.1 fast",
    "Veo 3",
    "Veo 3 fast",
    "Veo 2"
  ],
  grok: [
    "Grok 4.3",
    "Grok 4.20 Multi-Agent",
    "Grok 4.20 Reasoning",
    "Grok 4.20 Non-Reasoning",
    "Grok Build 0.1",
    "Grok Imagine Image",
    "Grok Imagine Image Quality",
    "Grok Imagine Video"
  ],
  anthropic: [
    "Claude Opus 4.7",
    "Claude Sonnet 4.6",
    "Claude Opus 4.6",
    "Claude Sonnet 4.5",
    "Claude Opus 4.5",
    "Claude Haiku 4.5",
    "Claude Opus 4.1",
    "Claude Sonnet 4",
    "Claude Opus 4"
  ],
  meta: [
    "Llama 4 Maverick (17B/128E, Instruct, FP8)",
    "Llama 4 Scout (17B/16E, Instruct, FP8)",
    "Llama 3.3 (70B, Instruct)",
    "Llama 3.3 (8B, Instruct)",
    "Llama 4 Maverick (Cerebras, 17B/128E, Instruct)",
    "Llama 4 Scout (Cerebras, 17B/16E, Instruct)",
    "Llama 4 Maverick (Groq, 17B/128E, Instruct)"
  ],
  vercel: ["v0 medium", "v0 medium (legacy)"],
  mistral: [
    "Mistral Small 4",
    "Mistral Medium 3",
    "Mistral Medium 3.5",
    "Mistral Large Latest"
  ],
  cohere: ["Command A Reasoning", "Command A"],
  moonshotai: ["Kimi K2.6", "Kimi K2.5", "Kimi K2 Thinking"],
  deepseek: ["DeepSeek V4 Pro", "DeepSeek V4 Flash", "DeepSeek R1"],
  zai: ["GLM 5.1", "GLM 5", "GLM 4.7", "GLM 4.6", "GLM 4.5"]
} as const;
