export const displayNameModelsByProviderImgGen = {
  openai: [
    "GPT-6 Sol",
    "GPT-6 Luna",
    "GPT-6 Astra",
    "GPT-5.6 Sol",
    "GPT-5.6 Terra",
    "GPT-5.6 Luna",
    "GPT-5.5",
    "GPT-5.5 Pro",
    "GPT-5.4",
    "GPT-5.4 Mini",
    "GPT-5.4 nano",
    "GPT-5.4 Pro",
    "GPT-5.2",
    "GPT-5.2 Pro",
    "GPT-5.1",
    "GPT-5",
    "GPT-5 Mini",
    "GPT-5 nano",
    "GPT-5 Pro",
    "GPT-4.1",
    "GPT-4.1 Mini",
    "GPT-4.1 nano",
    "GPT-4o",
    "GPT-4o Mini",
    "o3",
    "GPT-Image-2.5 Sunburst",
    "GPT-Image-2.5 Flare",
    "GPT-Image-2",
    "GPT-Image-1.5",
    "GPT-Image-1",
    "GPT-Image-1 mini"
  ],
  gemini: [
    "Nano Banana 2 Lite",
    "Nano Banana 2",
    "Nano Banana Pro",
    "Nano Banana",
    "Deep Research Max Preview (Apr-21-2026)",
    "Deep Research Preview (Apr-21-2026)"
  ],
  grok: [
    "Grok 4.7",
    "Grok 4.6",
    "Grok Imagine Image 2.0",
    "Grok Imagine Image",
    "Grok Imagine Image Quality"
  ],
  meta: ["Muse Image 1.0"]
} as const;
