export const modelIdToDisplayName = {
  openai: {
    "gpt-5.6-sol": "GPT-5.6 Sol",
    "gpt-5.6-terra": "GPT-5.6 Terra",
    "gpt-5.6-luna": "GPT-5.6 Luna",
    "gpt-5.5": "GPT-5.5",
    "gpt-5.4": "GPT-5.4",
    "gpt-5.4-mini": "GPT-5.4 mini",
    "gpt-5.4-nano": "GPT-5.4 nano",
    "gpt-5.2": "GPT-5.2",
    "gpt-5.2-chat-latest": "GPT-5.2 Chat",
    "gpt-5.1": "GPT-5.1",
    "gpt-5": "GPT-5",
    "gpt-5-mini": "GPT-5 mini",
    "gpt-5-nano": "GPT-5 nano",
    "gpt-5.1-chat-latest": "GPT-5.1 Chat",
    "gpt-5.3-codex": "GPT-5.3 codex",
    "gpt-5.2-codex": "GPT-5.2 codex",
    "gpt-5.1-codex-max": "GPT-5.1-Codex-Max",
    "gpt-5.1-codex": "GPT-5.1 Codex",
    "gpt-5.1-codex-mini": "GPT-5.1 Codex mini",
    "gpt-5-codex": "GPT-5-Codex",
    "gpt-5.5-pro": "GPT-5.5 pro",
    "gpt-5.4-pro": "GPT-5.4 pro",
    "gpt-5.2-pro": "GPT-5.2 pro",
    "gpt-5-pro": "GPT-5 pro",
    "gpt-5-chat-latest": "GPT-5 Chat",
    "gpt-4.1": "GPT-4.1",
    "gpt-4.1-mini": "GPT-4.1 mini",
    "gpt-4.1-nano": "GPT-4.1 nano",
    "gpt-4o": "GPT-4o",
    "gpt-4o-mini": "GPT-4o mini",
    "gpt-image-2": "GPT Image 2",
    "gpt-image-1.5": "GPT Image 1.5",
    "gpt-image-1": "GPT Image 1",
    "gpt-image-1-mini": "GPT Image 1 mini",
    "chatgpt-4o-latest": "chatgpt-4o-latest",
    "o4-mini": "o4-mini",
    "o4-mini-deep-research": "o4-mini-deep-research",
    "o3-deep-research": "o3-deep-research",
    o3: "o3",
    "o3-pro": "o3-pro",
    "o3-mini": "o3-mini",
    o1: "o1",
    "o1-pro": "o1-pro",
    "gpt-4": "GPT-4",
    "gpt-4-turbo": "GPT-4 turbo",
    "gpt-3.5-turbo": "GPT-3.5 turbo",
    "sora-2": "Sora 2",
    "sora-2-pro": "Sora 2 Pro"
  },
  gemini: {
    "gemini-3.7-flash": "Gemini 3.7 Flash",
    "gemini-3.6-flash": "Gemini 3.6 Flash",
    "gemini-3.5-flash-lite": "Gemini 3.5 Flash Lite",
    "gemini-3.5-flash": "Gemini 3.5 Flash",
    "gemini-3.1-pro-preview": "Gemini 3.1 Pro Preview",
    "gemini-3.1-pro-preview-customtools": "Gemini 3.1 Pro Preview Custom Tools",
    "gemini-3.1-flash-lite-preview": "Gemini 3.1 Flash Lite Preview",
    "gemini-3-flash-preview": "Gemini 3 Flash Preview",
    "gemini-3.1-flash-image-preview": "Nano Banana 2",
    "gemini-3.1-flash-lite-image": "Nano Banana 2 Lite",
    "gemini-3-pro-image-preview": "Nano Banana Pro",
    "gemini-2.5-flash-image": "Nano Banana",
    "gemini-omni-flash-preview": "Gemini Omni Flash Preview",
    "veo-3.1-generate-preview": "Veo 3.1",
    "veo-3.1-fast-generate-preview": "Veo 3.1 fast",
    "veo-3.1-lite-generate-preview": "Veo 3.1 lite",
    "lyria-3-pro-preview": "Lyria 3 Pro Preview",
    "lyria-3-clip-preview": "Lyria 3 Clip Preview",
    "gemini-2.5-pro": "Gemini 2.5 Pro",
    "gemini-2.5-flash": "Gemini 2.5 Flash",
    "gemini-2.5-flash-lite": "Gemini 2.5 Flash-Lite",
    "deep-research-max-preview-04-2026":
      "Deep Research Max Preview (Apr-21-2026)",
    "deep-research-preview-04-2026": "Deep Research Preview (Apr-21-2026)",
    "gemini-2.0-flash": "gemini-2.0-flash",
    "gemini-2.0-flash-lite": "gemini-2.0-flash-lite"
  },
  grok: {
    "grok-4.6": "Grok 4.6",
    "grok-4.5": "Grok 4.5",
    "grok-4.3": "Grok 4.3",
    "grok-4.20-multi-agent-0309": "Grok 4.20 Multi-Agent",
    "grok-4.20-0309-reasoning": "Grok 4.20 Reasoning",
    "grok-4.20-0309-non-reasoning": "Grok 4.20 Non-Reasoning",
    "grok-build-0.1": "Grok Build 0.1",
    "grok-imagine-image-2.0": "Grok Imagine Image 2.0",
    "grok-imagine-image": "Grok Imagine Image",
    "grok-imagine-image-quality": "Grok Imagine Image Quality",
    "grok-imagine-video": "Grok Imagine Video",
    "grok-imagine-video-1.5": "Grok Imagine Video 1.5"
  },
  anthropic: {
    "claude-opus-5": "Claude Opus 5",
    "claude-sonnet-5": "Claude Sonnet 5",
    "claude-fable-5": "Claude Fable 5",
    "claude-opus-4-8": "Claude Opus 4.8",
    "claude-opus-4-7": "Claude Opus 4.7",
    "claude-opus-4-6": "Claude Opus 4.6",
    "claude-sonnet-4-6": "Claude Sonnet 4.6",
    "claude-sonnet-4-5-20250929": "Claude Sonnet 4.5",
    "claude-opus-4-5-20251101": "Claude Opus 4.5",
    "claude-haiku-4-5-20251001": "Claude Haiku 4.5"
  },
  meta: {
    "muse-spark-1.2": "Muse Spark 1.2",
    "muse-spark-1.1": "Muse Spark 1.1"
  },
  vercel: {
    "v0-1.5-md": "v0 medium",
    "v0-1.0-md": "v0 medium (legacy)"
  },
  mistral: {
    "mistral-small-latest": "Mistral Small 4",
    "mistral-medium-3": "Mistral Medium 3",
    "mistral-medium-3.5": "Mistral Medium 3.5",
    "mistral-large-latest": "Mistral Large Latest"
  },
  cohere: {
    "command-a-plus-05-2026": "Command A Plus",
    "command-a-reasoning-08-2025": "Command A Reasoning",
    "command-a-03-2025": "Command A"
  },
  moonshotai: {
    "kimi-k3": "Kimi K3",
    "kimi-k2.7-code": "Kimi K2.7 Code",
    "kimi-k2.6": "Kimi K2.6",
    "kimi-k2.5": "Kimi K2.5",
    "kimi-k2-thinking": "Kimi K2 Thinking"
  },
  deepseek: {
    "deepseek-v4-pro-0813": "DeepSeek V4 Pro",
    "deepseek-v4-pro": "DeepSeek V4 Pro Preview",
    "deepseek-v4-flash": "DeepSeek V4 Flash",
    "deepseek-r1": "DeepSeek R1"
  },
  zai: {
    "glm-5.2": "GLM 5.2",
    "glm-5.1": "GLM 5.1",
    "glm-5": "GLM 5",
    "glm-4.7": "GLM 4.7",
    "glm-4.6": "GLM 4.6",
    "glm-4.5": "GLM 4.5"
  },
  alibaba: {
    "qwen3.8-max": "Qwen3.8-Max",
    "qwen3.7-max": "Qwen3.7-Max",
    "qwen3.7-plus": "Qwen3.7-Plus",
    "qwen3.7-flash": "Qwen3.7-Flash",
    "qwen3.6-plus": "Qwen3.6-Plus",
    "qwen3.5-plus": "Qwen3.5-Plus",
    "qwen3.5-flash": "Qwen3.5-Flash"
  },
  minimax: {
    "minimax-m3": "MiniMax-M3",
    "minimax-m2.7": "MiniMax-M2.7",
    "minimax-m2.5": "MiniMax-M2.5",
    "minimax-m2.1": "MiniMax-M2.1"
  },
  sakana: {
    "fugu-ultra": "Fugu Ultra",
    fugu: "Fugu",
    "fugu-cyber": "Fugu Cyber",
    "sakana-namazu": "Sakana Namazu"
  }
} as const;
