export const displayNameModelsByProvider = {
  openai: [
    "GPT-5.1",
    "GPT-5",
    "GPT-5 mini",
    "GPT-5 nano",
    "GPT-5.1 Chat",
    "GPT-5.1 Codex",
    "GPT-5.1 Codex mini",
    "GPT-5-Codex",
    "GPT-5 pro",
    "GPT-5 Chat",
    "GPT-4.1",
    "GPT-4.1 mini",
    "GPT-4.1 nano",
    "GPT-4o",
    "GPT-4o mini",
    "GPT Image 1",
    "GPT Image 1 mini",
    "DALL·E 3",
    "DALL·E 2",
    "ChatGPT-4o",
    "o4-mini",
    "o4-mini-deep-research",
    "o3-deep-research",
    "o3",
    "o3-pro",
    "o3-mini",
    "o1",
    "o1-pro",
    "GPT-4",
    "GPT-4 turbo",
    "GPT-3.5 turbo",
    "Sora 2",
    "Sora 2 Pro"
  ],
  gemini: [
    "Gemini 3 Pro Preview",
    "Gemini 2.5 Pro",
    "Nano Banana Pro",
    "Nano Banana",
    "Gemini 2.5 Flash",
    "Gemini 2.5 Flash-Lite",
    "Gemini 2.0 Flash",
    "Gemini 2.0 Flash-Lite",
    "Imagen 4",
    "Imagen 4 Fast",
    "Imagen 4 Ultra",
    "Veo 3.1",
    "Veo 3.1 fast",
    "Veo 3",
    "Veo 3 fast",
    "Veo 2"
  ],
  grok: [
    "Grok 4.1 Fast Reasoning",
    "Grok 4.1 Fast Non-Reasoning",
    "Grok 4",
    "Grok Code Fast 1",
    "Grok 4 Fast Reasoning",
    "Grok 4 Fast Non-Reasoning",
    "Grok 2 Image",
    "Grok 3",
    "Grok 3 Mini",
    "Grok 2 Vision"
  ],
  anthropic: [
    "Claude Sonnet 4.5",
    "Claude Opus 4.5",
    "Claude Haiku 4.5",
    "Claude Opus 4.1",
    "Claude Sonnet 4",
    "Claude Opus 4",
    "Claude Sonnet 3.7",
    "Claude Haiku 3.5",
    "Claude Haiku 3"
  ],
  meta: [
    "Llama 4 Maverick (17B/128E, Instruct, FP8)",
    "Llama 4 Scout (17B/16E, Instruct, FP8)",
    "Llama 3.3 (70B, Instruct)",
    "Llama 3.3 (8B, Instruct)",
    "Llama 4 Maverick (Cerebras, 17B/128E, Instruct)",
    "Llama 4 Scout (Cerebras, 17B/16E, Instruct)",
    "Llama 4 Maverick (Groq, 17B/128E, Instruct)"
  ],
  vercel: ["v0 medium", "v0 large", "v0 medium (legacy)"]
} as const;
