import { relative } from "node:path";
import type { UserConfig } from "tsdown";
import { defineConfig } from "tsdown";

export default defineConfig(
  options =>
    ({
      ...options,
      entry: [
        "src/index.ts",
        "src/alibaba/index.ts",
        "src/alibaba/sse.ts",
        "src/alibaba/types.ts",
        "src/anthropic/base.ts",
        "src/anthropic/index.ts",
        "src/anthropic/types.ts",
        "src/anthropic/vector-store.ts",
        "src/anthropic/workup.ts",
        "src/byte-codec/index.ts",
        "src/deepseek/index.ts",
        "src/deepseek/sse.ts",
        "src/deepseek/types.ts",
        "src/cohere/index.ts",
        "src/cohere/types.ts",
        "src/extract/index.ts",
        "src/gemini/chat.ts",
        "src/gemini/fss.ts",
        "src/gemini/index.ts",
        "src/gemini/types.ts",
        "src/gemini/workup.ts",
        "src/image/index.ts",
        "src/kimi/index.ts",
        "src/kimi/sse.ts",
        "src/kimi/types.ts",
        "src/logger/index.ts",
        "src/meta/index.ts",
        "src/minimax/index.ts",
        "src/minimax/sse.ts",
        "src/minimax/types.ts",
        "src/mistral/index.ts",
        "src/mistral/stream-content.ts",
        "src/mistral/types.ts",
        "src/mixins/index.ts",
        "src/models/index.ts",
        "src/openai/base.ts",
        "src/openai/gpt-image.ts",
        "src/openai/index.ts",
        "src/openai/responses-chat.ts",
        "src/openai/responses-img-gen.ts",
        "src/openai/types.ts",
        "src/openai/workup.ts",
        "src/pdf/index.ts",
        "src/prisma/attachment-provider.ts",
        "src/prisma/attachment.ts",
        "src/prisma/chat-request.ts",
        "src/prisma/chat-response.ts",
        "src/prisma/index.ts",
        "src/prisma/provider-store.ts",
        "src/prisma/tts.ts",
        "src/prisma/types.ts",
        "src/prisma/user-meta.ts",
        "src/prisma/user-store.ts",
        "src/prisma/utils.ts",
        "src/providers/index.ts",
        "src/resolver/asset-attach-or-paste.ts",
        "src/resolver/asset-compat.ts",
        "src/resolver/asset-complete.ts",
        "src/resolver/asset-fetch.ts",
        "src/resolver/chat-utils.ts",
        "src/resolver/chat.ts",
        "src/resolver/connection.ts",
        "src/resolver/convo-hydration.ts",
        "src/resolver/dispatch.ts",
        "src/resolver/index.ts",
        "src/resolver/tts.ts",
        "src/resolver/utils.ts",
        "src/sharp/index.ts",
        "src/store/types.ts",
        "src/store/vector-store.ts",
        "src/store/workup.ts",
        "src/tts/index.ts",
        "src/tts/types.ts",
        "src/types/index.ts",
        "src/vercel/index.ts",
        "src/vercel/sse.ts",
        "src/voyage/index.ts",
        "src/voyage/types.ts",
        "src/ws-server/index.ts",
        "src/xai/api-base.ts",
        "src/xai/api-methods.ts",
        "src/xai/base.ts",
        "src/xai/collections.ts",
        "src/xai/event-types.ts",
        "src/xai/img-gen.ts",
        "src/xai/index.ts",
        "src/xai/response-sse.ts",
        "src/xai/responses-api.ts",
        "src/xai/responses-types.ts",
        "src/xai/stream-workup.ts",
        "src/xai/sync.ts",
        "src/xai/types.ts",
        "src/xai/user-store.ts",
        "src/zai/index.ts",
        "src/zai/sse.ts",
        "src/zai/types.ts",
        "!src/__out__/**/*",
        "!src/test/**/*",
        "!src/tests/**/*",
        "!public/**/*"
      ],
      cwd: process.cwd(),
      target: ["node26"],
      fixedExtension: false,
      dts: { tsgo: true },
      watch: process.env.NODE_ENV === "development",
      format: ["esm"],
      sourcemap: true,
      tsconfig: relative(process.cwd(), "tsconfig.json"),
      clean: true,
      outDir: "dist",
      unbundle: true
    }) satisfies UserConfig
);
